### ISSUE TITLE
Switchable brake rails

### ISSUE THREAD

**Issue by lightonflux** [stujones11/minetest-railnet#4]
It is a bit annoying that brake rails brake all the time, at least in some scenarios. 

It would be nice to toggle them via mesecon. So they don't brake when they have power.

**Comment by stujones11** [comment]
They should be doing that already if you have mesecons installed, perhaps you have found a bug, try using the 'fixer' on the errant rails and/or the 'inspector' to view their meta-info

Note that these brake rails work the other way, they _should_ only break when they do have power

**Comment by lightonflux** [comment]
You are aright. It works as expected. The problem was the speed. To fast to be noticeable slowed down. 

Could you implement something that shows the current speed? So players can easily debug how much acceleration/deceleration they need?!
