### ISSUE TITLE
Moving objects to cart's inventory only moves one

### ISSUE THREAD

**Issue by wilkgr76** [stujones11/minetest-railnet#5]
Shift-clicking or normally moving a stack across will move only one and the remaining 98 are put back into your inventory. Shift+Click-spamming do work but will take 99 clicks, lots of time and a sore finger. Now imagine you want to send 24 stacks of cobble back to the surface if you're doing mining. That'd be a VERY sore finger...

**Comment by stujones11** [comment]
I hadn't noticed this, that is very annoying but hopefully there should be an easy fix.
