### ISSUE TITLE
Textures are nondecsript

### ISSUE THREAD

**Issue by Napiophelios** [stujones11/minetest-railnet#7]
Railnet is an awesome mod that needs better default textures
I have adapted some from Pixelbox by Gambit that are a bit more colorful.
https://github.com/stujones11/minetest-railnet/pull/6/commits/1348d098d7d38343af6aa4d00fc058ae3bd01238 

![screenshot_20160412_011809](https://cloud.githubusercontent.com/assets/8119411/14450512/f9ac0c82-004c-11e6-9b6c-87e3bef5214f.png)
![pixelbox_railcart by gambit](https://cloud.githubusercontent.com/assets/8119411/14450514/fd9cf630-004c-11e6-8571-5b5fc2bf8928.png)

**Comment by stujones11** [comment]
I must admit that Gambit's work is absolutely awesome but I will have check that the license permits this.

**Comment by HybridDog** [comment]
How do you think about adding diagonal steel stripes to make it look more stable?

**Comment by Napiophelios** [comment]
Diagonals would be hard to make look good in a 16px image.
I thought this might be better than the first proposal, 
![20160413171743](https://cloud.githubusercontent.com/assets/8119411/14509773/0d745b70-019c-11e6-9398-41860341b487.png)
it kinda looks sturdier :)
also removes the attention from the offset in the interior bottom texture

**Comment by stujones11** [comment]
The new cart texture has been merged, thank you for your contribution.
